version: "3"
services:
  app:
    build: .
    command: yarn dev
    volumes:
      - .:/vale-do-chopp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: vale_do_chopp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
