version: "3"
services:
  app:
    build: .
    command: yarn dev
    volumes:
      - .:/vale-do-chopp
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:admin@10.0.10.164:8080/vale_do_chopp
